language: python
python:
- 3.6
#addons:
#  apt:
#    packages:
#    - pandoc
deploy:
- provider: pypi
  distributions: sdist bdist_wheel
  user: al_kricha
  password:
    secure: kSDrEw9gExCwsCnFblr+XK6fbPz+cudNhmypZhDxFUxIteCARSLuy0O027RhaWbmK3AM1L7DXjVa7tS51DmjyhewpOs+w98f1soDYOQKOF2VEKsRTKBgLV6hJyswcALuP8QUutGNNVHRsObXmMBNRsnJ9DKHW5epTveNaZRW1HLuP0fuHC+HSE6FwVewC05gGSDjURAXHU5qkjoSnQGhep7H4QMBQfKmnizr8149br6XGrAE7fftVTSWkMY7LHibybfgFF2mEDb2votkm3fhf/P5Hi+HlFnsciX+NU748wNWW1/I0/BztgbbVh4F0DBFrvhIa5yCU4PQcygsTFhvKVtn51GMVOJ22vkNEMK2YWt0dcD3oixygTtwIs/TKsDq3+ls6Msxpr9pC2MIxoxa2a7jjeBWlWuazFJFgRW7GcXgp1nGfZKsBUUwtUBbBtksNcR5w2VNTUBrHvmHrhvSyKt1fc5JOtLX8Bb69CfYvplFJnWmm4MEpjNuQwdqp9e9PVIee54TlHKd4/swSk4s9VxJoN+yfqy1E7YPvuzNm3+rMti6XfNtHOnai2pdhzgCN2b/A7wUtNKOE5U1Y598HjTFeOAaxbV2yq0fSeRiRjNJyHRNcIoLH9Xc2c+ptGhHqjPXl9n7z22MYZWml+w3vupkYY4HTMDjmG9fcmHhkec=
  on:
    branch: master
    tags: true
script: nosetests
